version: "2.1"
services:
  influx:
    image: influxdb:1.7
    environment:
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
      - INFLUXDB_READ_USER=grafana
      - INFLUXDB_READ_USER_PASSWORD=grafana
    volumes:
      - ./contrib/influxdb-init.iql:/docker-entrypoint-initdb.d/influxdb-init.iql:ro
      - influxdata:/var/lib/influxdb
  grafana:
    image: grafana/grafana:7.1.1
    ports:
      - "8000:3000"
    depends_on:
      - influx
    volumes:
      - grafanadata:/var/lib/grafana
      - ./contrib/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml:ro
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    # This is a simple hack to give rabbitmq 10 seconds
    # to get up and running. Otherwise grafana tries to
    # connect too soon and crashes.
    healthcheck:
      test: rabbitmqctl list_queues
      interval: 10s
      timeout: 15s
      retries: 5
    volumes:
      - rabbitdata:/var/lib/rabbitmq
  telegraf:
    image: telegraf
    depends_on:
      rabbit:
        condition: service_healthy
    volumes:
      - ./contrib/telegraf.conf:/etc/telegraf/telegraf.conf:ro
volumes:
  influxdata:
  grafanadata:
  rabbitdata:
