# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99b238d45994389a6822bacf5329785669a1682dae661b015035bfe85921081c8ddb00145b3bb358766b0cc4941c7772a3bb9c387be14a3ecf474b523566e32

test:
  secret_key_base: 3563f426e9ad3ada75b1d66cba1a799409831df46378183cd34cb3897650446970977112c498a603a56b0baf4da681ff848beae215acf89e5786ac2dea8e1736

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
